-- begin SCHOOLMANAGEMENT_SCHOOL_CLASS
alter table SCHOOLMANAGEMENT_SCHOOL_CLASS add constraint FK_SCHOOLMANAGEMENT_SCHOOL_CLASS_ON_SCHOOL foreign key (SCHOOL_ID) references SCHOOLMANAGEMENT_SCHOOL(ID)^
create index IDX_SCHOOLMANAGEMENT_SCHOOL_CLASS_ON_SCHOOL on SCHOOLMANAGEMENT_SCHOOL_CLASS (SCHOOL_ID)^
-- end SCHOOLMANAGEMENT_SCHOOL_CLASS
-- begin SCHOOLMANAGEMENT_STUDENT_SCHOOL_CLASS
alter table SCHOOLMANAGEMENT_STUDENT_SCHOOL_CLASS add constraint FK_STUSCHCLA_ON_STUDENT foreign key (STUDENT_ID) references SCHOOLMANAGEMENT_STUDENT(ID)^
alter table SCHOOLMANAGEMENT_STUDENT_SCHOOL_CLASS add constraint FK_STUSCHCLA_ON_SCHOOL_CLASS foreign key (SCHOOL_CLASS_ID) references SCHOOLMANAGEMENT_SCHOOL_CLASS(ID)^
-- end SCHOOLMANAGEMENT_STUDENT_SCHOOL_CLASS
