###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.springContextConfig = +com/company/schoolmanagement/web-spring.xml

cuba.dispatcherSpringContextConfig = +com/company/schoolmanagement/web-dispatcher-spring.xml

cuba.persistenceConfig = +com/company/schoolmanagement/persistence.xml

cuba.metadataConfig = +com/company/schoolmanagement/metadata.xml

cuba.viewsConfig = +com/company/schoolmanagement/views.xml

cuba.windowConfig = +com/company/schoolmanagement/web-screens.xml

cuba.menuConfig = +com/company/schoolmanagement/web-menu.xml

cuba.permissionConfig = +com/company/schoolmanagement/web-permissions.xml

cuba.mainMessagePack = +com.company.schoolmanagement.web

cuba.anonymousSessionId = ab7343d6-3a7b-b9f2-a3cb-18b5b3a6ab30

cuba.creditsConfig = +

###############################################################################
#                                  Other                                      #
###############################################################################

# Middleware connection
cuba.connectionUrlList = http://localhost:8080/app-core

# Set to false if the middleware works on different JVM
cuba.useLocalServiceInvocation = true

cuba.webContextName = app
cuba.availableLocales = English|en
cuba.localeSelectVisible = false
cuba.web.theme = hover