###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.dbmsType = hsql

cuba.springContextConfig = +com/company/schoolmanagement/spring.xml

cuba.persistenceConfig = +com/company/schoolmanagement/persistence.xml

cuba.metadataConfig = +com/company/schoolmanagement/metadata.xml

cuba.viewsConfig = +com/company/schoolmanagement/views.xml

cuba.mainMessagePack = +com.company.schoolmanagement.core

cuba.keyForSecurityTokenEncryption = JTw7ZN8OYRSsiw8v

cuba.anonymousSessionId = ab7343d6-3a7b-b9f2-a3cb-18b5b3a6ab30

###############################################################################
#                                  Other                                      #
###############################################################################

cuba.webContextName = app-core
cuba.availableLocales = English|en
cuba.localeSelectVisible = false

cuba.dataSourceProvider = application
cuba.dataSource.username = sa
cuba.dataSource.password =
cuba.dataSource.dbName = schoolmanagement-567742
cuba.dataSource.host = localhost
cuba.dataSource.port = 9010